### ISSUE TITLE
Run audit of dependencies during CI

### ISSUE THREAD

**Issue by MaximDevoir** [probot/create-probot-app#104]
Run an audit of dependencies from root package lockfile and all template lockfiles during CI pipeline. 

Additionally, should Snyk be added to the repository? It’s free for open-source projects and can be easily integrated into the pipeline by adding the Snyk application from the GitHub marketplace.

Finally, I believe GitHub has a feature of warning repository owners of vulnerabilities as they become known - as well as applying fixes to the package.json and lockfile files.

See probot/probot#1079

**Comment by gr2m** [comment]
What does Snyk provide that GitHub's security vulnerability alerts don't provide yet? 

And if you run the audit during CI, it would only log the warnings, unless you plan to push changes back to the repository?

We could run `npm audit fix` on a schedule and create a pull request if anything changes.

**Comment by MaximDevoir** [comment]
I think using GitHub's [automated security update](https://help.github.com/en/github/managing-security-vulnerabilities/configuring-automated-security-updates#managing-automated-security-updates-for-your-repository) feature for the CPA repo is the way to go. My problem is I don't have access to the repository's [security alets](https://github.com/probot/create-probot-app/network/alerts), so I won't know when a new alert is created or be able to run the recommended actions from an alert (e.g. action to create a PR with recommended changes).

I think Greenkeeper in combination with GitHub security updates should be enough to maintain dependencies.

I no longer think we need to add anything to the CI; GitHub Security Alerts > Snyk; and because GitHub will alert us with newly discovered vulnerabilities, we can use that as our "*CI*".

**Comment by gr2m** [comment]
I've added you to the list of people with access to security alerts:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/39992/70001861-40909300-1513-11ea-8c43-6286ef460c4f.png">

I never used that before, but I think it does what we want :)

**Comment by MaximDevoir** [comment]
I don't appear to be added. The Alerts tab is not available to me. It should be visible, even if there are no active alerts.

![Screenshot from 2019-12-04 23-25-36](https://user-images.githubusercontent.com/10104630/70213096-683b5300-16ed-11ea-9c64-282d3d99d5bf.png)

**Comment by gr2m** [comment]
That's super odd, you were no longer added. I've added you again, can you check if you see it now?

**Comment by MaximDevoir** [comment]
Yup, I see it now. :smiley:
