### ISSUE TITLE
What version of Node is required?

### ISSUE THREAD

**Issue by hawkins** [probot/create-probot-app#106]
Hey! :wave: Absolutely love Probot, but I've recently found myself in an environment where I'm limited in what Node versions are available to me. I've found that using Node 10, I'm unable to run create-probot-app due to syntax errors from dependencies.

Is there a specific Node version I should be aiming to use? Or should this instead be a fight of pinning dependency versions down?

Here's the error I'm getting today:

```
create-probot-app my-app
/usr/lib/node_modules/create-probot-app/node_modules/chalk/source/index.js:103
	...styles,
	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/create-probot-app/bin/create-probot-app.js:19:33)
```

**Comment by hawkins** [comment]
FWIW, I was able to run with Node 10 by:

- cloning this repo
- pinning `chalk` to `^2.0.0`
- `$ npm i`
- `$ npm run build`
- `$ sudo npm link`
- ` $ create-probot-app my-app` :heavy_check_mark:

**Comment by MaximDevoir** [comment]
That's odd. Both Probot and Create Probot App support Node v8 and up.

What happens when you run `npx create-probot-app --version` or `npx create-probot-app -v`?

**Comment by hawkins** [comment]
This may be different than what you expect since I had to clone the repo and make this change to package.json to get it installed:

```diff
--- a/package.json
+++ b/package.json
@@ -32,7 +32,7 @@
   },
   "homepage": "https://github.com/probot/create-probot-app#readme",
   "dependencies": {
-    "chalk": "^3.0.0",
+    "chalk": "^2.0.0",
     "commander": "^4.0.1",
     "conjecture": "^0.1.2",
     "cross-spawn": "^7.0.1",
```

...


```
$ npx create-probot-app --version
Create Probot App v0.0.0-development

$ npm ls -g create-probot-app
/opt/rh/rh-nodejs10/root/usr/lib
└── (empty)
```

**Comment by MaximDevoir** [comment]
The only major breaking change in Chalk v3 is they dropped support for anything below Node.js 8. With v3, the syntax was updated to support Node v8 and up. If Node.js is unable to recognize the spread operator `...`, then the files are getting executed by an older version of Node.js (e.g. Node.js 6).

**Comment by hawkins** [comment]
That's really interesting... yeah, I remember using spread plenty, but always in Babel settings so I wasn't sure if that was standard syntax yet or not. At this point, I think it's clear what someone who needs this to run on older Node versions needs to do (pin chalk and install), so I'm going to close this because it's evident there's nothing to be done. The rest must be something weird about my environment on this machine to have run Node <8 when I had Node 10 installed and at npx etc.

Thanks for chiming in to double check me!
