### ISSUE TITLE
Update documentation for new UI

### ISSUE THREAD

**Issue by bkeepers** [probot/create-probot-app#11]
https://github.com/probot/create-probot-app/pull/10 made some nice improvements to the questions asked when creating a new app, however, the documentation on https://probot.github.io/docs/development/#generating-a-new-app still shows the output from the old app.

It'd be great to update the docs on the website to show the output of the command now.

cc @JasonEtco

**Comment by adsrc** [comment]
@bkeepers I would like to work on this. Please assign this to me.

**Comment by bkeepers** [comment]
@adsrc We're glad you're eager to contribute! The best way to do this is just to open a pull request with the fix. Let us know if you have any questions or run into problems fixing it.

**Comment by adsrc** [comment]
@bkeepers I'm on it!

**Comment by JasonEtco** [comment]
Closed by https://github.com/probot/probot/pull/275 🎉
