### ISSUE TITLE
create-probot-app typescript's `build:watch` not work because of noUnusedLocals

### ISSUE THREAD

**Issue by jtratner** [probot/create-probot-app#131]
## Bug Report

**Current Behavior**
On first run of the typescript template from create-probot-app, tsc will fail because of `noUnusedLocals` option being forced to `True`

```
›› npx create-probot-app my-first-app
<... select basic-ts ...>
›› cd my-first-app
›› npm run dev

> my-first-app@1.0.0 dev /Users/jtratner/tmp/my-first-app
> npm run build:watch


> my-first-app@1.0.0 build:watch /Users/jtratner/tmp/my-first-app
> tsc && (tsc -w --preserveWatchOutput & nodemon)

node_modules/@octokit/types/src/generated/Endpoints.ts(4,1): error TS6133: 'Url' is declared but its value is never read.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! my-first-app@1.0.0 build:watch: `tsc && (tsc -w --preserveWatchOutput & nodemon)`
```

**Expected behavior/code**
Expect it to run `build:watch` without error :)

**Environment**
- Probot version(s): [e.g. v6.0.0]
- Node/npm version: Node 12.6.0; npm 6.14.4
- OS: 10.13.6

**Possible Solution**
Set `noUnusedLocals: false` in compilerOptions

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by gr2m** [comment]
The `'Url' is declared but its value is never read` was likely caused by a bad `@octokit/types` release. Can you please make sure to update it to [v2.7.1](https://github.com/octokit/types.ts/releases/tag/v2.7.1)

**Comment by jtratner** [comment]
Totally understand that - but doesn’t probot need to update its required
version too?

I didn’t think I could update a transitive dependency...

**Comment by gr2m** [comment]
you need to update your lock file. The safest way is to delete `package-lock.json` and the `node_modules/` folder, then run `npm install` again

**Comment by jtratner** [comment]
Okay I’ll try it!

To be clear this is from a totally fresh use of `npx create-probot-app`. I’ll wipe the environment entirely and see if it recurs.

**Comment by jtratner** [comment]
okay yes relocking (or, in my case, wiping out and re-running `npx create-probot-app`) fixed the whole thing.  I'm just surprised because I swear I tried wiping it out and rerunning it on multiple separate days 😓 

Thanks for the help and apologies if I wasted your time! ✌️

**Comment by gr2m** [comment]
no apologies needed, probably just unlucky timing, and it was my bad `@octokit/types` that caused all this trouble in the first place :) Thanks for the update, glad it's working now!
