### ISSUE TITLE
package-lock.json should not be added to gitignore

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [probot/create-probot-app#137]
According to the [official documentation](https://docs.npmjs.com/configuring-npm/package-lock-json.html) for `package-lock.json`, the file should be committed into the source control but all the templates are generated with the file in the `.gitignore`.

Is there any particular reason for it being added to the `.gitignore`. If not, maybe it should be removed.

**Comment by gr2m** [comment]
I think this has most likely legacy reasons, coming from a time when npm's lock file was more painful than helpful. I think we can remove it from the `.gitignore` files. Would you mind sending a PR?

**Comment by SayakMukhopadhyay** [comment]
Sure, I will create a PR with the changes.
