### ISSUE TITLE
Document the difference between each template

### ISSUE THREAD

**Issue by lukepighetti** [probot/create-probot-app#138]
```
? Which template would you like to use? 
❯ basic-js 
  basic-ts 
  checks-js 
  git-data-js 
  deploy-js 
```

There are no descriptions of the different templates and how to select the appropriate one. The names are also not clear as to what their purpose is. I don't see this in the documentation anywhere.

**Comment by gr2m** [comment]
I agree, it would be nice to add a short description to each template at that step. Thoughts @MaximDevoir?

**Comment by MaximDevoir** [comment]
I agree that's a great idea. Unfortunately, my time is limited during the ongoing COVID-19 pandemic and will unavailable until early June.

**Comment by lukepighetti** [comment]
If someone can write 5 words about each one I'll make a PR.

**Comment by gr2m** [comment]
I also don't know :D But maybe check out the respective index files and derive what they do from that

- basic-js: https://github.com/probot/create-probot-app/blob/master/templates/basic-js/index.js
- basic-ts: https://github.com/probot/create-probot-app/blob/master/templates/basic-ts/src/index.ts
- checks-js: https://github.com/probot/create-probot-app/blob/master/templates/checks-js/index.js
- deploy-js: https://github.com/probot/create-probot-app/blob/master/templates/deploy-js/index.js
- git-data-js: https://github.com/probot/create-probot-app/blob/master/templates/git-data-js/index.js

**Comment by lukepighetti** [comment]
Alright :D fair enough

**Comment by gr2m** [comment]
We would still love a pr for this, if anyone is interested in helping out!

**Comment by lukepighetti** [comment]
What's blocking it is I have no idea what each template does

**Comment by gr2m** [comment]
- basic-js: Comment on new issues
- basic-ts: Comment on new issues - written in TypeScript
- checks-js: Handle check_suite request and rerequested actions
- deploy-js: Creates a deployment on a pull request event
- git-data-js: Opens a PR every time someone installs your app for the first time

I think we should rename `git-data-js` to `create-pull-request-js`

**Comment by shaftoe** [comment]
I'll have a look at this soon
