### ISSUE TITLE
Remove nodemon & standard from template dependencies

### ISSUE THREAD

**Issue by gr2m** [probot/create-probot-app#158]
All templates currently include `nodemon` and `standard` as dependencies. 

I think these are out of scope for probot, they slow down testing and throw lots of errors during the install process. I think we should remove them and only leave

1. `probot` as the sole production dependency
2. `smee-client`, `jest`, and `nock` as dev dependencies.

Any objections?

**Comment by shaftoe** [comment]
@gr2m it looks like meanwhile `nodemon` and `standard` are gone. Anything left to be done here?

**Comment by gr2m** [comment]
nope that's done, thanks for checking @shaftoe!
