### ISSUE TITLE
Descriptions are not auto-populated into template

### ISSUE THREAD

**Issue by jbjonesjr** [probot/create-probot-app#22]
The template files contained within https://github.com/probot/template expect the **description** information to be contained in `description`, ie:

```
{
  "name": "{{ name }}",
  "version": "1.0.0",
  "description": "{{{ description }}}",
  "author": "{{{ author }}}",
```
https://github.com/probot/template/blob/011af1fe2095ea3eeec84553c7d4781378b59540/package.json#L1-L5

while the create script stores it under the variable `desc` , ie:
https://github.com/probot/create-probot-app/blob/aefa4b695a80c28be7d53cef468e59cf8288d96d/bin/create-probot-app.js#L47-L55

Wasn't sure if I should open the PR here or in the template repo.

**Comment by bkeepers** [comment]
Good catch. I think that should be updated here.
