### ISSUE TITLE
Always use the latest version of probot

### ISSUE THREAD

**Issue by bkeepers** [probot/create-probot-app#3]
It currently uses https://github.com/probot/plugin-template/blob/master/package.json. We either need to figure out how to automate keeping that up to date (greenkeeper @gr2m?) , or figure out another way to install the latest version when generating a new plugin

h/t @hiimbex

**Comment by JasonEtco** [comment]
If we go the automation route, we can fetch the latest semver from the registry then plunk that into the `package.json`. It won't be `@latest` but it will be the "most recent version"

**Comment by gr2m** [comment]
you only need to update it when the new `probot` version published to npm is out of range of what is defined in https://github.com/probot/plugin-template/blob/master/package.json. A simple way to do that is to activate greenkeeper. You also want to release new versions of `create-probot-plugin` automatically when the `probot` dependency changes, we can use [semantic-release](https://github.com/semantic-release/semantic-release) for that, but you need the `npm test` script to return exit code 0, as it’s releasing via travis and runs the tests first

**Comment by hiimbex** [comment]
I'm 👍 for adding greenkeeper here since we got it figured out on the other probot repos. Especially since we should prioritize keeping the version of probot in this repo up to date.

**Comment by JasonEtco** [comment]
Woops, not sure why my PR closed this. Sorry folks!

**Comment by hiimbex** [comment]
it was the `resolve` keyword. I noticed and figured it was on accident :slightly_smiling_face:

**Comment by JasonEtco** [comment]
It's supposed to underline keywords like that 😑

**Comment by gr2m** [comment]
note that if `package-lock.json` exists, you currently need to setup a workaround for Greenkeeper to work, it will tell you on the initial PR, too: https://github.com/greenkeeperio/greenkeeper-lockfile#npm

**Comment by bkeepers** [comment]
> I'm 👍 for adding greenkeeper here since we got it figured out on the other probot repos.

I don't know if greenkeeper will work since the [package.json has placeholders](https://github.com/probot/template/blob/master/package.json) that NPM thinks are invalid.

**Comment by gr2m** [comment]
oh yeah that won’t work, Greenkeeper is only looking for a package.json file in the root folder, sorry. I think there is an open issue for this on Greenkeeper, but for now we have to build a custom solution for it. It shouldn’t be too hard:tm:, here is an example of little node app that receives hooks from npm for a specific package and sends a message about it to slack: https://glitch.com/edit/#!/npm-release-to-slack-message We could create a pull request or directly update the file instead?

**Comment by gr2m** [comment]
> oh yeah that won’t work, Greenkeeper is only looking for a package.json file in the root folder, sorry

This is no longer the case:
https://blog.greenkeeper.io/announcing-greenkeeper-3-1504f5113998

I’ve yet to look into the exact setup, but I think it should be possible now

**Comment by gr2m** [comment]
Do you still want me to look into it?
