### ISSUE TITLE
"test" GitHub action should fail when tests print warnings

### ISSUE THREAD

**Issue by shaftoe** [probot/create-probot-app#309]
See example here: https://github.com/probot/create-probot-app/runs/1631489000?check_suite_focus=true#step:4:171

```js
 RUNS  test/index.test.js
WARN	 (Deprecation): [probot] "id" option is deprecated. Use "appId" instead
```

This could help ensure that template apps are up to date with the latest APIs. I'm trying to understand if there's such a built in feature in `jest` but I couldn't find yet, another way could be to add some logic to the Bash script.

I'm also wondering if it does make sense to have tests run via Bash given that probably part of the logic in `create-probot-app.ts` could be factored out and used for testing the template apps too.

Also, shouldn't [node-version here](https://github.com/probot/create-probot-app/blob/4f4019be89b19c4ee53e6e59d7364816bca8fa43/.github/workflows/test.yml) be upgraded to v14/v15?

**Comment by shaftoe** [comment]
> I'm trying to understand if there's such a built in feature in jest but I couldn't find yet

A [relevant discussion](https://github.com/facebook/jest/issues/6121) which seems to suggest this relatively [simple solution](https://stackoverflow.com/questions/28615293/is-there-a-jest-config-that-will-fail-tests-on-console-warn/50584643#50584643) (or should I say workaround? I guess it's mostly a matter of taste) that makes use of the `setupFiles` Jest feature.

**Comment by gr2m** [comment]
> Also, shouldn't [node-version here](https://github.com/probot/create-probot-app/blob/4f4019be89b19c4ee53e6e59d7364816bca8fa43/.github/workflows/test.yml) be upgraded to v14/v15?

Yes, let's test in 10, 12, 14, 15, see https://nodejs.org/en/about/releases/. I'm working on automating the nodejs version matrix automatically, it keeps getting out of date ...

Also `actions/setup-node@v1` should now be `actions/setup-node@v2`.

**Comment by shaftoe** [comment]
Addressed by https://github.com/probot/create-probot-app/pull/310
