### ISSUE TITLE
Various cleanups proposal

### ISSUE THREAD

**Issue by shaftoe** [probot/create-probot-app#315]
I'd like to address all the final bits missing to consider this project as stable, for example fix some of the `TODOs` left in the code, so to shift my focus elsewhere, for example docs or the new `app-setup` project you were mentioning elsewhere.

I list a few here:

- https://github.com/probot/create-probot-app/blob/b0f6342d1b5b5852eb16b07c072ec35abd733434/src/create-probot-app.ts#L3

  Sort how? is there any best practice in TS for the import sequence? [how about this](https://vxlabs.com/2020/10/06/sort-typescript-import-groups-from-standard-to-local/)?

- https://github.com/probot/create-probot-app/blob/b0f6342d1b5b5852eb16b07c072ec35abd733434/src/create-probot-app.ts#L194

  Can you elaborate on this? maybe point me to some example of _object combining_? I can't find anything useful searching for `design patterns + object combining`

- Do you mind if I move some of the logic out of `main()` and into dedicated functions? not functionally necessary of course, I personally find it a good way to add useful documentation and make it easier to fix/maintain, similarly as I did [here essentially](https://github.com/probot/create-probot-app/blob/f0d96d8c5c52ad065daf154de40455d3279de63a/script/test-template.sh), i.e. an outstanding list of tasks in `main()` and each actual task implementation in its own function.

- Instead of `simple-git + spawn` should we maybe use a native Node library like [nodegit](https://www.nodegit.org/) or others to ensure better portability?

- More in general, if you think there are missing improvements or things you'd like to see changed or removed, let me know

**Comment by gr2m** [comment]
> // TODO: Sort imports

Ignore it, it's not worth the extra overhead. This is a legacy comment, we can remove it

> // TODO: clean that up into nicer object combining

I don't know what it means, the comment was added by @MaximDevoir. Max, can you recall what you meant there?

> Do you mind if I move some of the logic out of `main()` and into dedicated functions?

Not at all, I agree with your points

>  Instead of `simple-git + spawn` should we maybe use a native Node library like [nodegit](https://www.nodegit.org/) or others to ensure better portability?

I'm not sure if `nodegit` is fully compatible. If you'd like to experiment with it, feel free, but let's do that in a separate PR. I don't mind the current setup, I cannot recall any OS compat problems in the past

> More in general, if you think there are missing improvements or things you'd like to see changed or removed, let me know

will do! Thanks a lot for your help!

**Comment by shaftoe** [comment]
I've nothing against `spawn` but my guess is that at least for `npm` there's no real need for it, see https://github.com/probot/create-probot-app/pull/316

I hope that's also a first step towards readability (i.e. split logic into dedicated functions)

**Comment by MaximDevoir** [comment]
> // TODO: clean that up into nicer object combining

I believe this is another legacy comment that refers to the repetitiveness of `answers`' properties being assigned to themself OR to the corresponding `program` property. The goal may have been to use a pattern out there that can be more easily readable.

https://github.com/probot/create-probot-app/blob/6775d441df545d1f27439ffd5a5ad51255628b0c/src/create-probot-app.ts#L206-L214

**Comment by shaftoe** [comment]
@MaximDevoir can you provide an example of such a pattern, possibly in TS? TBH I'm not that confident yet with design patterns 😅 or should we just get rid of the comment and live with it as is?

**Comment by MaximDevoir** [comment]
@shaftoe The thing that has always been obvious to me would be to merge the objects with `Object.assign`, or to create a separate object that uses the [spread operator](https://mariusschulz.com/blog/object-rest-and-spread-in-typescript) to merge objects.

I think it would look something like this:

```diff
diff --git a/src/create-probot-app.ts b/src/create-probot-app.ts
index e166a77..332f0b7 100644
--- a/src/create-probot-app.ts
+++ b/src/create-probot-app.ts
@@ -252,21 +252,18 @@ async function main(): Promise<void> {
   );
 
   const answers = await inquirer.prompt(questions);
-  answers.author = stringifyAuthor({
-    name: program.author || answers.author,
-    email: program.email || answers.email,
-  });
-  answers.template = answers.template || program.template;
-  answers.toBuild = answers.template.slice(-3) === "-ts";
-  answers.year = new Date().getFullYear();
-  answers.camelCaseAppName = camelCase(program.appName || answers.appName);
-  answers.appName = program.appName || answers.appName;
-  answers.description = program.desc || answers.description;
-  answers.user = answers.owner = program.user || answers.user;
-  answers.repo = program.repo || answers.repo;
-  // TODO: clean that up into nicer object combining
-
-  sanitizeBy(answers, ["author", "description"]);
+  const mergedAnswers = {...answers, ...program, ...{ // a more appropriate variable name is out there
+    author: stringifyAuthor({
+      name: answers.author,
+      email: answers.email,
+    }),
+    year: new Date().getFullYear(),
+    camelCaseAppName: camelCase(program.appName || answers.appName), // is this being used?
+    toBuild: answers.template.slice(-3) === "-ts",
+    description: program.desc || answers.description,
+    owner: program.user || answers.user,
+  }}
+  sanitizeBy(mergedAnswers, ["author", "description"]);
```


It looks a lot cleaner, but there would need to be a bit of testing to ensure nothing breaks.

For example: 

* With `answer` property assignments, the `answers` property is pulled first, then the `program` property is pulled if the previous value is falsey. and visa-versa. Why do some pull from `answers` first, and others from `program`? Is this a by design?

**Comment by shaftoe** [comment]
@MaximDevoir thanks for the clarification. As for your question, I don't know anything about the reasoning behind pulling from both `answers` and `program`, I'm basically just going through the code and asking about the TODOs left there.

**Comment by MaximDevoir** [comment]
@shaftoe Inquirer doesn't support default values if `when` is supplied (see https://github.com/SBoudrias/Inquirer.js/issues/740). We have to pull from `answers`, and then from `program` incase the value was set directly via the CLI.

**Comment by shaftoe** [comment]
I'm still not entirely sure about the soundness of [this logic here](https://github.com/probot/create-probot-app/blob/2df06fda04abd61d68444698b72f837d19b0aa86/src/helpers/filesystem.ts#L28), when I'm done with reviewing it I'll consider this issue closed unless someone has other improvements/cleanups to suggest

**Comment by shaftoe** [comment]
I think this can be closed, https://github.com/probot/create-probot-app/pull/339 addressed my last concern about the code base status 🍾
