### ISSUE TITLE
Difficult to extend for use case templates

### ISSUE THREAD

**Issue by hiimbex** [probot/create-probot-app#34]
Re https://github.com/probot/probot/issues/620 and https://github.com/probot/template/pull/79 we want to extend create-probot-app to work for multiple use cases in the same repo. The current library we [use](https://github.com/probot/create-probot-app/blob/032d479e1b33a6874d491e098ae4a020f4620c3a/bin/create-probot-app.js#L131-L133) for that is [egad's scaffold](https://github.com/boneskull/egad) which wasn't designed for our usecase in several ways. 

Most importantly right now it doesn't support just cloning a folder from a git repo. In fact, I'm struggling to find a library that does do that. So I started out writing it using our [get contents API](https://developer.github.com/v3/repos/contents/#get-contents); however, it's really hard to handle directories within directories without some recursion. You can check out what I started [here](https://github.com/probot/create-probot-app/commit/47f02e708260e5465c74212362db7beb600c1f45) (naturally I committed my PAT 🤦‍♂️ ); however, at this point I'm leaning towards just having different templates in different branches instead of folders. That set up is supported by our existing frameworks.

I'd love to hear other thoughts/if folders feel important enough for this additional complexity to the create-probot-app script, or if branches might be simpler.
cc/ @probot/maintainers

**Comment by bkeepers** [comment]
For posterity, @hiimbex and I talked through a couple alternatives:

1. Move the templates into this repository and distribute them with the `create-probot-app` package. This will require copying over the templating features form egad, but it's not that much code.
2. Update egad or something similar to support subdirectories. it might still require cloning the entire repo (or downloading the zip from GitHub), but it could just use the subdirectory to for templating.

cc @boneskull
