### ISSUE TITLE
CPA cannot find NPM module when running via NPX

### ISSUE THREAD

**Issue by MaximDevoir** [probot/create-probot-app#340]
A bug occurs in Create-Probot-App@4.4.10+ that results in Node being unable to resolve the `npm` module.

Prior to CPA@4.4.10, we were running NPM via `cross-spawn`. Now, we've been running npm via module import.

I won't be able to dive too much into this issue, but I still think this is an NPX issue and not necessarily a CPA issue - although I could be wrong.

Adding `npm` as a `dependency` to `package.json` so that npm will be locally installed, which NPX should be able to resolve, should fix the bug.

```sh
> npx create-probot-app@4.4.9
npx: installed 229 in 13.838s
create-probot-app [options] <destination>
  Argument <destination> is required.
  Example:
    create-probot-app my-first-app
  Run create-probot-app --help to see all options.

> npx create-probot-app@4.4.10
npx: installed 231 in 12.637s
Cannot find module 'npm'
```

**Comment by gr2m** [comment]
it looks like starting with https://github.com/probot/create-probot-app/pull/316 we depend on the `npm` package, but we missed to add it to dependencies:

https://github.com/probot/create-probot-app/pull/316/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R30-R45
