### ISSUE TITLE
 "url" wasn't supplied error upon first start

### ISSUE THREAD

**Issue by helaili** [probot/create-probot-app#346]
When running `npm start` right after `npx create-probot-app ...` in order to register the app, I'm getting this error: 

<img width="635" alt="Screen Shot 2021-01-23 at 14 58 18" src="https://user-images.githubusercontent.com/2787414/105580310-e3494800-5d8b-11eb-9440-2320a22f6d84.png">

Adding a `homepage` entry in `package.json` solves it.

**Comment by MaximDevoir** [comment]
Thank you for reporting this issue... and you even have the solution :smile:. That makes hotfixing considerably easier.

This is fixed by #347.
