### ISSUE TITLE
Add validity checks of `package.json` to tests

### ISSUE THREAD

**Issue by shaftoe** [probot/create-probot-app#348]
Ref: https://github.com/probot/create-probot-app/issues/346

**Comment by MaximDevoir** [comment]
The `name`, `homepage`, and `description` properties are read from package.json in [probot/manifest-creation](https://github.com/probot/probot/blob/master/src/manifest-creation.ts#L45-L63). However, only `homepage` is required (see [GitHub Manifest Parameters](https://docs.github.com/en/developers/apps/creating-a-github-app-from-a-manifest#github-app-manifest-parameters)).

**Comment by shaftoe** [comment]
![D697C288-2DFD-4159-BE7E-4D0BCA5E440A](https://user-images.githubusercontent.com/281389/106391495-d1038580-63ed-11eb-91d1-13a1f8e5b1b8.jpeg)

Can anyone here explain me how these labels are supposed to be used? @MaximDevoir ?

**Comment by MaximDevoir** [comment]
Whoops, I didn't mean to remove the label. Just unassign myself. You can re-add it.

**Comment by shaftoe** [comment]
Nah, don't worry, I was just trying to understand if I got something wrong, forget about it

**Comment by shaftoe** [comment]
@gr2m this was the last enhancement I had in mind for CPA, I'm ready and willing to jump on the _configure_ project you were mentioning a while ago if you're still of that idea 👍
