### ISSUE TITLE
Add watch mode to immediately rebuild Typescript app on file change

### ISSUE THREAD

**Issue by borNfreee** [probot/create-probot-app#35]
Add watch mode to immediately rebuild Typescript app on file change.

Currently, to update the final `./lib/index.js`, I need to

* `npm run build`
* `npm run dev`

**Comment by kentaro-m** [comment]
Add `nodemon.json` to rebuild ts files in src dir every time files change. 

```json
{
  "events": {
    "restart": "npm run build"
  },
  "watch": [
    "src/**/*"
  ],
  "ext": "ts"
}
```
