### ISSUE TITLE
Tests should not skip Git initialization

### ISSUE THREAD

**Issue by shaftoe** [probot/create-probot-app#350]
ATM each template test skips `git init` logic, we should ensure that gets tested all right too, e.g.

- create the temp folder under /tmp
- check the commit is correctly created

**Comment by MaximDevoir** [comment]
Git initialization is skipped when running within another Git repo. This comes from here:

https://github.com/probot/create-probot-app/blob/fb17d98a19739d655625156c2ae4945ec0882422/src/helpers/init-git.ts#L47

I think the theory is when running CPA in a git repo, the user probably intends to add the project to the parent git repo, and not have a git repo within a git repo.

Tests could move to a temporary directory using something like `testing_template_directory=$(mktemp -d -t cpa-XXXXXXXXXX)`.
