### ISSUE TITLE
Dependabot doesn't work as expected

### ISSUE THREAD

**Issue by shaftoe** [probot/create-probot-app#366]
All recent new PR are odd, eg `package.json` doesn't get updated as expected.

We should investigate into it and either fix it or find alternatives.

**Comment by MaximDevoir** [comment]
The primary `package.json` or one of the template files?

What is currently happening and what is expected?

**Comment by shaftoe** [comment]
I'm referring to the primary one (I'm not even convinced the templates' ones get actually updated, I can't remember any PR about these).

For example have a look at the latest two:

- https://github.com/probot/create-probot-app/pull/367
- https://github.com/probot/create-probot-app/pull/368

For both there's no trace of updates to `package.json` as I'd expect. For #367 there's also another odd bit. i.e. subject says `bump semantic-release from 17.3.7 to 17.3.8` but [current one](https://github.com/probot/create-probot-app/blob/e6b116df51fe3d725bcd6327962dd2e561668fb4/package.json#L62) in `package.json` is `^17.1.1`

**Comment by gr2m** [comment]
> For both there's no trace of updates to `package.json` as I'd expect. For #367 there's also another odd bit. i.e. subject says `bump semantic-release from 17.3.7 to 17.3.8` but [current one](https://github.com/probot/create-probot-app/blob/e6b116df51fe3d725bcd6327962dd2e561668fb4/package.json#L62) in `package.json` is `^17.1.1`

I guess `17.3.8` is still within the range of `^17.1.1` so the package.json is not updated?

**Comment by MaximDevoir** [comment]
Dependabot updates package.json differently from package-lock.json. By default, it should widen `package.json` dependencies when there is an out-of-range version change, and updates `package-lock.json` when there are updates within the version range for the package.

![53266487-c821b980-36d8-11e9-8a2e-69abb393bab6](https://user-images.githubusercontent.com/10104630/107391465-92389400-6aad-11eb-9180-e3d597f2a621.png)

Just as Gregor described, semantic-release shouldn't be updated in `package.json` until v18 comes out - but will continue to be updated in the lockfile.

**Comment by shaftoe** [comment]
Thanks for the clarification, I opened this mostly as a reminder for myself to better understand dependabot behavior, good to see it's actually working as expected
