### ISSUE TITLE
README instructions seem incorrect

### ISSUE THREAD

**Issue by yeskunall** [probot/create-probot-app#39]
I did `npm init probot-app [--typescript] test` and expected it to create a folder called `test`. Instead, after I filled in all the choices (where once again I provided `test` as the app name, I got this:

![image](https://user-images.githubusercontent.com/14703164/47535155-4fc0fe00-d888-11e8-9681-c9ef3714b4f7.png)

... a folder called [--typecsript]. 😅

For now just reporting this; I might take a look into it later (_but no guarantees!_)

**Comment by yeskunall** [comment]
![](https://media.giphy.com/media/Q7aMDI2jO37vW/giphy.gif)


... I think I just had a brain fart. I really appreciate you explaining it so nicely to me tho! I don't know what happened, but I just blindly copied the command, and expected it to work. I think it's partially because I'm used to doing that, because they just work out of the box.

And yes, I'm still glad I made this issue, because I feel like there's gonna be more than one person who's gonna do the exact same thing as me 😅

I'd love to look into this ASAP!

💖

**Comment by dmlittle** [comment]
As for the user experience, if the script detects that `[--typescript]` was input as the directory name, it could warn saying something along the lines of 
> It looks like you tried creating a typescript project but passed in `[--typescript]` as the output directory name instead. Try using the flag `--typescript` without the brackets instead.

**Comment by hiimbex** [comment]
This option has been entirely deprecated and replace with a (hopefully) better script experience!!
