### ISSUE TITLE
--typescript option specified in docs is no longer valid

### ISSUE THREAD

**Issue by C-Saunders** [probot/create-probot-app#40]
It looks like the `--typescript` option was removed in b203255293b7807a4fde245523cc275ca3e67539, but it wasn't removed from [the docs](https://probot.github.io/docs/development/#generating-a-new-app).

Does it make more sense to
* Re-add this option (likely mapping it to `--template=basic-ts` from what I can see)
* Remove `[--typescript]` from the docs
* Update the to reflect the current state of the `--template` option
* Something else entirely

It's possible this should be an issue in the docs repo, but I guess it depends on how this gets resolved and this seemed like an okay entry point. I apologize if this was incorrect.

**Comment by hiimbex** [comment]
Yea @TimonVS kindly opened https://github.com/probot/probot/pull/752 to solve this :)

**Comment by hiimbex** [comment]
This should be up-to-date on the docs website now!
