### ISSUE TITLE
Add JSDoc header to basic-js template

### ISSUE THREAD

**Issue by JasonEtco** [probot/create-probot-app#54]
This:

```
/**
 * @param {import('probot').Application} app
 */
```

Is missing here:

https://github.com/probot/create-probot-app/blob/f9cbf8a7ce8b147bc7b02f6833457d1d808b1da7/templates/basic-js/index.js#L1-L5

So we don't get that sweet sweet autocomplete by default!

**Comment by tcbyrd** [comment]
Yeh I went back and forth on this. On the one hand it's nice for autocomplete, but if you're just a JS user it _might_ be confusing to see a comment at the top that you aren't sure what it does? Maybe we could also document why it's there, though 🤔

**Comment by JasonEtco** [comment]
Totally reasonable. Commenting about a comment seems... weird; but I'm not opposed 🤷‍♂️ I do think the benefit of having it outweighs the confusion.
