### ISSUE TITLE
[help wanted] error while installing node dependencies in create-probot-app

### ISSUE THREAD

**Issue by prakashujjwal1010** [probot/create-probot-app#55]
it is showing error while installing node dependencies in create-probot-app.
`npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.`
so, when i cd to project directory and try `npm install` , still i am getting error.
`npm ERR! Unexpected end of JSON input while parsing near '...:"7.0.0-alpha.18","ba'`.

**Comment by Stevefb** [comment]
@prakashujjwal1010  - I'm having the same problem, did you get this figured out at all?

As far as I can tell the file `package.json` is being added (or looked for) in the wrong place.  I get the same problem whether I use the npx or yarn command.

Would be great if someone could verify this... _(package in wrong place)_

created file: 
`C:\Users\steve\Documents\GitHub\ProBot\myAppName\package.json `

but I think it should be created here: 
`C:\Users\steve\Documents\GitHub\ProBot\package.json `

Things progress a bit further if I manually move package.json up one level, but then I get a different error:

> npm ERR! Refusing to install package with name "myAppName" under a package
> npm ERR! also called "myAppName". Did you name your project the same
> npm ERR! as the dependency you're installing?

I can get further again if I delete everything except package.json and change "myAppName" to "myDifferentAppName".  Then I end up with:

> Installing Node dependencies!
> npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
 
> + live-issues@1.0.0
> added 1 package from 1 contributor in 2.197s
> 
> Done! Enjoy building your Probot app!

So... it looks good, but not very confidence inspiring.

I was also having a bunch of problems with python, but that seems to have sorted itself out...

**Comment by Ninjas-in-Pajamas** [comment]
I am getting the same error, except mine is telling me

npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file

**Comment by MaximDevoir** [comment]
This issue is similar to #85 

It appears that the program fails while trying to install Node modules.

This issue should be solved with #80 and #86 . In the meantime, `cd` into the generated app and manually `npm install`. We'll roll out a fix for this soon.

**Comment by gr2m** [comment]
@prakashujjwal1010 could you try again please?
