### ISSUE TITLE
Run tests of all templates

### ISSUE THREAD

**Issue by gr2m** [probot/create-probot-app#60]
This repository would be much easier to maintain if we had a setup which would run all tests of all templates. We would love help with this!

**Comment by gr2m** [comment]
Maybe the test could be a base script which

1. `cd`s into each template folder
2. Set a valid name in `package.json` using the [package-write](https://github.com/MauriceButler/package-write) module, e.g. `npx package-write name test`
3. run `npm ci && npm test`

**Comment by hiimbex** [comment]
https://github.com/probot/create-probot-app/blob/master/script/test ?

**Comment by gr2m** [comment]
🤦‍♂️ I was looking for a test script in package.json and totally missed that this already exists! Thansk!
