### ISSUE TITLE
TypeError: this.breakLines(...).flat is not a function

### ISSUE THREAD

**Issue by michalfita** [probot/create-probot-app#679]
```
$ npx create-probot-app hadean-police
npx: installed 497 in 60.872s

Let's create a Probot app!
Hit enter to accept the suggestion.

TypeError: this.breakLines(...).flat is not a function
```

Please fix of provide instruction for the workaround.

**Comment by shaftoe** [comment]
Hello @michalfita , can you please provide some context? like:

- what Operating System
- which version of NodeJS / npx you're using
- other information that could help understand why it doesn't work on your system

Thanks!

**Comment by michalfita** [comment]
@shaftoe These details in: https://github.com/probot/probot/issues/1669
Sorry for reporting in both, but I've noticed stale issues here.

**Comment by shaftoe** [comment]
Closing because of duplication

**Comment by shaftoe** [comment]
@michalfita no worries. I'll close this now to avoid duplications, let's use that issue only from now on.
