### ISSUE TITLE
Missing .gitignore file

### ISSUE THREAD

**Issue by lucasmichot** [probot/create-probot-app#69]
Hello Probot team;
I've noticed that when generating a bot from a template, the `.gitignore` file is never copied.
Which means that it always has to be added manually after 

This is also related to https://github.com/probot/create-probot-app/issues/42

**Comment by jeffslofish** [comment]
I looked into this issue and it appears that the packages on npm do not contain the .gitignore files in the templates/* folders.

To verify this, I created a new package with create-probot-app as a dependency at version 3.1.0 (or any 3.x.x version). Then `npm install` and check the `node_modules/create-probot-app/templates/*` folders and note that there is not any .gitignore files.

However, if create-probot-app is simply downloaded from github, `npm install` is run, and then the `create-probot-app/bin/create-probot-app.js` script is run, then the .gitignore file is generated as expected, so the script is not to blame, it is this missing .gitignore file on npm.
