### ISSUE TITLE
Invalid package.json when including quotation marks in author's full name

### ISSUE THREAD

**Issue by kevinkassimo** [probot/create-probot-app#74]
For example, with name `Kevin "Kassimo" Qian`, I am getting
```
"author": "Kevin "Kassimo" Qian <kevinkassimo@gmail.com>",
```
in generated `package.json`, the quotation marks are not escaped, resulting in a failed npm install. This happens when the author has e.g. a nickname to include.

**Comment by MaximDevoir** [comment]
PR #78 will fix this issue by escaping double-quotes.
