### ISSUE TITLE
create-probot-app installs probot ^7.2.0

### ISSUE THREAD

**Issue by singsai** [probot/create-probot-app#76]
I've tested this out with both basic and checks:

`npx create-probot-app` creates a probot where its `package.json` specifies version `^7.2.0`

I noticed the problem because my target repo wasn't reading my `.github` repo's `.github/config.yml` file. Once I updated the version to `9.3.3`, it worked fine.

I've gone through the create-probot-app repo to see if I can find the problem, but the templates look fine: `"probot": "^9.0.1"` is what I see in all of the `package.json` templates. So the problem may be occurring elsewhere.

**Comment by MaximDevoir** [comment]
The version for `probot` in all templates is `^9.0.1` on the `master` branch. However, the latest release - [3.1.0](b516e3c0e84dda2d490d17076f6ac988c13132a8) - is using older dependencies. 

A new release needs to be deployed.

**Comment by gr2m** [comment]
I've published 3.1.1
