### ISSUE TITLE
Change "Package name" in prompts

### ISSUE THREAD

**Issue by JasonEtco** [probot/create-probot-app#8]
Now that we've more-or-less ironed out the wording around creating Apps (not plugins or packages), I'd like to tighten up the wording here. Currently, the first question `create-probot-app` asks the user is "Package name." This should probably say something like "What is the name of your App?" or "What is your App called?"

Relevant code:
https://github.com/probot/create-probot-app/blob/ff4d722c90225c2f468f984011b36bdbbf6f5a2e/bin/create-probot-app.js#L19

Opening this up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) participants 🎉 Feel free to jump on this if you're interested!

**Comment by rwaskiewicz** [comment]
@JasonEtco Mind if I give this a shot?

**Comment by JasonEtco** [comment]
@rwaskiewicz not at all, go for it!

**Comment by lucianolucianoluciano** [comment]
#9

**Comment by rwaskiewicz** [comment]
Create #10 for this issue.  I hadn't realized @lucianolucianoluciano had submitted a PR for it as well.  Feel free to cherry pick from what I've got there or just close it out as a duplicate if needed 🙂

**Comment by JasonEtco** [comment]
@lucianolucianoluciano - thank you for submitting that #9! Because @rwaskiewicz had already mentioned that he'd be jumping on this issue, I'll close out your PR. Sorry!

@rwaskiewicz - Awesome! I've left a comment on your PR, but other than the one tiny thing it looks great.

**Comment by JasonEtco** [comment]
Closed by #10 🎉
