### ISSUE TITLE
The programmatic API was removed in npm v8.0.0

### ISSUE THREAD

**Issue by nipundavidnagarro** [probot/create-probot-app#834]
## Bug Report

Unable to create the project using npx command, 

**Current Behavior**
Node version 19 also tried with lower version of node (16)

```js
// Your code here
npx create-probot-app my-first-app
```

**Expected behavior/code**
should have create the project 

**Environment**

- Probot version(s): [e.g. v6.0.0]
- Node/npm version: [e.g. Node 16,19/npm 7, 8]
- MacOS Big Sur 11.4

**Comment by wolfy1339** [comment]
This has been fixed in the latest release of `create-probot-app`

**Comment by kaf-lamed-beyt** [comment]
Awesome!!
