### ISSUE TITLE
TypeError: this.breakLines(...).flat is not a function

### ISSUE THREAD

**Issue by michalfita** [probot/create-probot-app#835]
## Bug Report

**Current Behavior**
On attempt to follow the documentation to create the new bot:
```
$ npx create-probot-app hadean-police
npx: installed 497 in 60.872s

Let's create a Probot app!
Hit enter to accept the suggestion.

TypeError: this.breakLines(...).flat is not a function
```

**Expected behavior/code**
As presented in https://probot.github.io/docs/development/#generating-a-new-app

**Environment**

- Probot version(s): 🤷🏼 
- Node/npm version: node v10.19.0 / npm 6.14.4
- OS: WSL2 on Windows 11 with ubuntu 20.04

**Possible Solution**

Fix the tool, that's it.

**Additional context/Screenshots**
This prevents me from starting work on a bot I need for my team.
Reported as well in https://github.com/probot/create-probot-app/issues/679

**Comment by wolfy1339** [comment]
This issue has been fixed in the latest version of `create-probot-app`.

In the next major version of Probot v13, only NodeJS 18+ is supported
