### ISSUE TITLE
basic-ts does not compile in v5.1.0

### ISSUE THREAD

**Issue by jinhyoo-mp** [probot/create-probot-app#859]
run `npx create-probot-app app-name`
select "basic-ts"
cd app-name
run `npm run build`

Would expect this to compile but it throws a bunch of compiler errors

**Comment by wolfy1339** [comment]
please share the generated code, as well as any errors from the typescript compiler

**Comment by wolfy1339** [comment]
Also, please share NodeJS version and TypeScript version

**Comment by wolfy1339** [comment]
Unfortunately, the `node-lru` package types are broken with recent versions of TypeScript. The author of the package is unwilling to backport the fix.
See https://github.com/isaacs/node-lru-cache/issues/355

Those errors are safe to ignore
